name: setupx
description: Simple Login & Register App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
